### ISSUE TITLE
APPSCREATOR HTML

### ISSUE THREAD

**Issue by Ajisan03** [ZazerConer/Templates-For-AppCreator24#1]
Hi bro any idea how to get this work on appscreator24?

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://mrpw.ptmnc01.verspective.net/?deviceId=ZGFkZmZkZjItYzQ1Mi0zM2RiLTk0OWQtM2M2YmY1YzZjMDNi
#EXTINF:-1 tvg-id="ANT.ID" tvg-logo="https://static.epg.best/id/ANTV.id.png" group-title=" INDONESIA",ANTV
https://liveanevia.mncnow.id/live/eds/ANTV/sa_dash_vmx/ANTV.mpd

**Comment by ZazerConer** [comment]
Appcreator24 already has a video player to play ".mpd" videos (ExoPlayer). But if the video you play in ExoPlayer can't be played or does not support, I recommend you use this video player (ShakaPlayer+Key). Go here : https://github.com/ZazerConer/TV_CHANNEL_HTML/blob/main/video_player/ShakaPlayer.html

**Comment by Ajisan03** [comment]
<script src="/player.js"></script> 
            <script src="/dist/shaka-player.compiled.js"></script>
        <script>
    var data = {
            drm: 'aHR0cHM6Ly9jcm9zMDEubm9udG9uYm9sYS5teS5pZC9odHRwczovL21ycHcucHRtbmMwMS52ZXJzcGVjdGl2ZS5uZXQvP2RldmljZUlkPU5qY3dZV0kyWkdFdFl6RTRZaTB6WldGbExUbGpPV1l0WkdFek9HSXdZV0ZqTjJJMQ==',
            widevine: 'aHR0cHM6Ly9saXZlYW5ldmlhLm1uY25vdy5pZC9saXZlL2Vkcy9SQ1RJLUREL3NhX2Rhc2hfdm14L1JDVEktREQubXBk',
        }
</script>


Did i input it correctly?
